In [31]:
import numpy as np

def gini(actual, pred, cmpcol = 0, sortcol = 1):
     assert( len(actual) == len(pred) )
     all = np.asarray(np.c_[ actual, pred, np.arange(len(actual)) ], dtype=np.float)
     #print all 
     all = all[ np.lexsort((all[:,2], -1*all[:,1])) ]
     print all 
     
     totalLosses = all[:,0].sum()
     print 'totalLosses', totalLosses
     giniSum = all[:,0].cumsum().sum() / totalLosses
     print 'giniSum', giniSum
     giniSum -= (len(actual) + 1) / 2.
     print 'giniSum', giniSum
     return giniSum / len(actual)
 
def gini_normalized(a, p):
     return gini(a, p) / gini(a, a)

In [34]:
a = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1]
p = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.5,0.4,1,1,1,1]
#gini(a, a)
gini_normalized(a, p)

[[  1.    1.   16. ]
 [  1.    1.   17. ]
 [  1.    1.   18. ]
 [  1.    1.   19. ]
 [  0.    0.5  14. ]
 [  1.    0.4  15. ]
 [  0.    0.    0. ]
 [  0.    0.    1. ]
 [  0.    0.    2. ]
 [  0.    0.    3. ]
 [  0.    0.    4. ]
 [  0.    0.    5. ]
 [  0.    0.    6. ]
 [  0.    0.    7. ]
 [  0.    0.    8. ]
 [  0.    0.    9. ]
 [  0.    0.   10. ]
 [  0.    0.   11. ]
 [  0.    0.   12. ]
 [  0.    0.   13. ]]
totalLosses 5.0
giniSum 17.8
giniSum 7.3
[[  1.   1.  15.]
 [  1.   1.  16.]
 [  1.   1.  17.]
 [  1.   1.  18.]
 [  1.   1.  19.]
 [  0.   0.   0.]
 [  0.   0.   1.]
 [  0.   0.   2.]
 [  0.   0.   3.]
 [  0.   0.   4.]
 [  0.   0.   5.]
 [  0.   0.   6.]
 [  0.   0.   7.]
 [  0.   0.   8.]
 [  0.   0.   9.]
 [  0.   0.  10.]
 [  0.   0.  11.]
 [  0.   0.  12.]
 [  0.   0.  13.]
 [  0.   0.  14.]]
totalLosses 5.0
giniSum 18.0
giniSum 7.5


0.97333333333333349